### ISSUE TITLE
Is it possible to authorize on substream level?

### ISSUE THREAD

**Issue by mauron85** [primus/substream#19]
Firstly thanks for nice work.

Is it possible to authorize on substream level?

I would like to create two namespaces: public and private.

Public should be accessible without any authorization and private should be allowed to access only for authorized users only.

From primus docs I see authorize is on primus top level.

```
primus.authorize(...);
```

And substreams are initiated on connection (after authorization)

```
  primus.on('connection', function(spark) {
    var public = spark.substream('public');
    var private = spark.substream('private');

    // my goal is to do authorization for private substream only
   private.authorize(...); // not sure if this is possible
 }
```

**Comment by lpinca** [comment]
No, this feature it is currently not supported by `substream` as it works on an already "authorized" connection.

**Comment by mauron85** [comment]
Ok, no problem. In my case it is not very useful anyway due https://github.com/primus/primus/issues/501#issuecomment-256741447
